spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ccreater.top:63306/backend?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH-mm-ss


server:
  port: 8088
  servlet:
    context-path: /
  secret-key: AA546ADF546safd35444sfd
  image-folder: static
  api-path: api
  admin-path: public

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:/com/team/backend/mapper/**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
wxMini:
  appId: wx5cb3151fe9a79b35
  secret: 6f6dc11730700a996d1731e9718c5a86
wxMiniReal:
  appId: wxbc7325a534e7461c
  secret: 25e1f70d9703b0c33679b43923afdbf0

test:
  istest: 1